### PR TITLE
feat: support react-native-reanimated styles

### PR DESCRIPTION
**Pull request by headfire94**
Depends on https://github.com/ExodusMovement/shakl/pull/12
https://app.asana.com/0/1202332025965022/1206950508328923/f

Issue: 
when create component using shakl with pre-defined styles and then pass animated styles to it, `react-native-reanimated` ignores pre-defined styles, it works only with animated once. 
Solution:
Split our animated and pre-defined styles in array: `[style, animatedStyle]`.

In theory this can be probably solved on `react-native-reanimated` lib level, somewhere here https://github.com/software-mansion/react-native-reanimated/blob/e88fb10d902ab73c3de8d916bc2c7f9a9d3069ad/src/createAnimatedComponent.js#L252-L262, but right now they explicitly recommend to:
> Only define the dynamic part of your styles with useAnimatedStyle and keep the static ones separately using StyleSheet API or (if you really have to) with inline styles. That way you avoid lots of unnecessary style recalculations. Static and dynamic styles can be easily merged using the [] syntax:

### CODE REVIEW

**Review by alexandrius — APPROVED** [review]
Looks great! Thanks

**Comment by alexandrius** [comment]
While you are on it can you add `text` prop support to `styled.Text`?
Right now you can do that like `styled.Text().attrs({children:"text"})`

**Comment by headfire94** [comment]
> While you are on it can you add `text` prop support to `styled.Text`? Right now you can do that like `styled.Text().attrs({children:"text"})`

added task https://app.asana.com/0/1202332025965022/1206967317746870/f

**Review by andrejborstnik — APPROVED** [review]
utACK

**Pull request merged**
