### PR TITLE
feat: types

### PR DESCRIPTION
**Pull request by alexandrius**
Closes: https://app.asana.com/0/1202332025965022/1205700522198310

- Adds types to `shakl`
- Adds `Image` as default export
- Types work with dynamic components too 
- Drops rollup

Screenshot 2023-10-12 at 8 17 33 PM
Screenshot 2023-10-12 at 8 17 51 PM
Screenshot 2023-10-12 at 8 18 16 PM

### CODE REVIEW

**Comment by sonaye** [comment]
Why drop rollup? Shakl works in the DOM too this breaks it

**Comment by alexandrius** [comment]
@sonaye Brought `rollup` back.

Ideally we should have 2 different packages.

**Comment by alexandrius** [comment]
@sonaye How do you prefer to proceed? 
While this:
```
"react-native": "lib/rn.js",
```
works internally, VSCode ignores it. 

I think we better have 2 packages:
`shakl-react-native` and `shakl`

We can leave with this approach too. Types work well

**Comment by sonaye** [comment]
@alexandrius prefer to not break things and keep one package, can this be merged as it's or it won't work?

**Comment by alexandrius** [comment]
@sonaye now the change doesn't break anything apart false types on dom

**Comment by sonaye** [comment]
@alexandrius you can self merge and publish a new version

**Pull request merged**
